const desserts = [
  {
    imageSrc: "/src/assets/images/image-waffle-mobile.jpg",
    name: "Waffle with Berries",
    category: "Waffle",
    price: 6.5,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-creme-brulee-mobile.jpg",
    name: "Vanilla Bean Crème Brûlée",
    category: "Crème Brûlée",
    price: 7.0,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-macaron-mobile.jpg",
    name: "Macaron Mix of Five",
    category: "Macaron",
    price: 8.0,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-tiramisu-mobile.jpg",
    name: "Classic Tiramisu",
    category: "Tiramisu",
    price: 5.5,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-baklava-mobile.jpg",
    name: "Pistachio Baklava",
    category: "Baklava",
    price: 4.0,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-meringue-mobile.jpg",
    name: "Lemon Meringue Pie",
    category: "Pie",
    price: 5.0,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-cake-mobile.jpg",
    name: "Red Velvet Cake",
    category: "Cake",
    price: 4.5,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-brownie-mobile.jpg",
    name: "Salted Caramel Brownie",
    category: "Brownie",
    price: 4.5,
    isSelected: false,
    quantity: 1,
  },
  {
    imageSrc: "/src/assets/images/image-panna-cotta-mobile.jpg",
    name: "Vanilla Panna Cotta",
    category: "Panna Cotta",
    price: 6.5,
    isSelected: false,
    quantity: 1,
  },
];

export default desserts;
